---
title: "pratica06_2026_09_21"
author: "Leila Kawanishi"
format: pdf
editor: visual
---

## GROUP BY

# Intruções
No arquivo me315.sqlite encontram-se as tabelas PRESERVE e EMPLOYEE criadas na aula anterior.
Importe o banco de dados no https://www.sqliteview.com/app ou configure o Rstudio (Posit Cloud) para trabalhar com SQLIte

```{r}
install.packages("DBI")
install.packages("RSQLite")
library(DBI)
library(RSQLite)

con <- dbConnect(RSQLite::SQLite(), "../me315.sqlite")
dbListTables(con)
```
```{sql connection=con}
SELECT * FROM PRESERVE

```
```{sql connection=con}
SELECT * FROM EMPLOYEE


```


#  SINTAXE

SELECT grouping_column, funcao_de_agregacao FROM Tabela
WHERE condicao
GROUP BY grouping_column

- WHERE sempre é antes do GROUP BY

1.  Para cada estado mencionado na tabela PRESERVE, exiba o número total de acres de todas as áreas de preservação localizadas nesse estado.

```{sql connection=con}
SELECT STATE, SUM(ACRES) FROM PRESERVE
GROUP BY STATE

```

2.  Modifique a consulta de exemplo anterior de modo que apenas as linhas com valores de PNO menores que 12 sejam consideradas.
```{sql connection=con}
SELECT STATE, SUM(ACRES) FROM PRESERVE
WHERE PNO < 12
GROUP BY STATE

```

3.  Exiba a tabela de resultados da consulta de exemplo anterior. Ordene os resultados em ordem crescente, de acordo com os totais resumidos.
```{sql connection=con}
SELECT STATE, SUM(ACRES) FROM PRESERVE
WHERE PNO < 12
GROUP BY STATE
ORDER BY 2
```

4.  Para cada estado mencionado na tabela PRESERVE, exiba o número total de acres e o número de reservas naturais por estado. Estamos apenas interessados nas reservas com PNO menores a 10. Ordene os resultrados pero número de reservas por estado (de forma decrescente)
```{sql connection=con}
SELECT STATE, SUM(ACRES) AS SOMA, COUNT(*) AS NUM FROM PRESERVE
WHERE PNO < 10
GROUP BY STATE
ORDER BY NUM DESC

```

5.  Exiba o código do estado e a taxa média de admissão por estado que possua uma área de preservação natural com mais de 1.000 acres.
```{sql connection=con}
SELECT STATE, AVG(FEE) FROM PRESERVE
WHERE ACRES > 1_000
GROUP BY STATE

```

6.  Para cada estado mencionado na tabela PRESERVE, calcule a área total, em acres, de todas as suas áreas de preservação. Em seguida, exiba cada STATE e sua área total, somente se esse total for superior a 15.000 acres.
```{sql connection=con}
SELECT STATE, SUM(ACRES) AS TOTAL FROM PRESERVE
GROUP BY STATE
HAVING TOTAL > 15_000

```


# HAVING
Sintaxe:

HAVING condicao


- A clausula HAVING deve estar logo depois do GROUP BY
- A condição deve referenciar a um resultado intermediario produzido pela clausula GROUO BY

7.  No exercício anterior, não considere as áreas de preservação de Montana. Exiba cada estado e sua área total, em acres, somente se essa área total for superior a 15.000 acres.
```{sql connection=con}
SELECT STATE, SUM(ACRES) AS TOTAL FROM PRESERVE
WHERE STATE <> 'MT'
GROUP BY STATE
HAVING TOTAL > 15_000

```

8.  Exiba os valores mínimo e máximo de área, em acres, das áreas de preservação natural localizadas em cada estado, desde que o valor mínimo de ACRES seja superior a 10 acres e o valor máximo de ACRES seja inferior a 20.000 acres. Exiba o código do estado, juntamente com seus valores mínimo e máximo de área.
```{sql connection=con}
SELECT STATE, MIN(ACRES), MAX(ACRES) FROM PRESERVE
GROUP BY STATE
HAVING MIN(ACRES) > 10 and MAX(ACRES) < 20_000

```

9.  'Determine a área total, em acres, para cada estado e, em seguida, exiba o menor desses totais.
```{sql connection=con}
SELECT STATE, SUM(ACRES) FROM PRESERVE
GROUP BY STATE
ORDER BY SUM(ACRES)
LIMIT 1

```

10. BONUS
```{sql connection=con}
SELECT STATE, SUM(ACRES) AS TOTAL
FROM PRESERVE
GROUP BY STATE
UNION ALL
SELECT 'TOTAL', SUM(ACRES)
FROM PRESERVE;
```

