---
title: "lab04_leila_kawanishi_277185"
author: "Leila Kawanishi"
format: pdf
editor: visual
---

## Laboratório 4: Importação de Dados Retangulares - Excel
Benilton Carvalho


# Conjunto de Dados
O conjunto de dados em questão é o conjunto de índices de desenvolvimento mundial, disponibilizado pelo Banco Mundial através do link http://datatopics.worldbank.org/world-development-indicators/.

# Expectativas
Ao fim deste laboratório, você deverá ser capaz de:

- Importar dados de planilhas específicas de arquivos em formato Excel;
- Trabalhar com variáveis cujos nomes fogem do padrão usual de programação (por exemplo, variáveis com espaços brancos em seus nomes);
- Selecionar variáveis do interesse;
- Verificar se os dados estão no formato tidy e transformá-los para tal formato;
- Optar apropriadamente entre filtering joins e mutating joins;
- Produzir visualizações de dados de séries temporais;


# Atividades
Q1. Carregue os pacotes readxl e tidyverse.

Q2. Crie uma variável chamada fname que contenha o caminho para o arquivo WDIEXCEL.xlsx, disponível no seu diretório de dados. Confirme que o R identifica a existência do arquivo utilizando o comando file.exists

Q3. Leia a planilha “Country” e armazene no objeto countries.

Q4. Mantenha apenas os registros de 5 países (Brasil e outros 4 de sua escolha).

Q5. Leia a planilha “Data” e armazene no objeto WDI.

Q6. Selecione apenas as colunas:

- Country Code
- Indicator Code
- E todos os anos de 1960-2018
Q7. Confirme se os dados wm WDI estão em formato tidy. Se não estiverem, transforme-os para tal formato. Faça de forma que exista uma coluna referente ao ano chamada YEAR.

Q8. Confirme se a coluna referente ao ano está em formato inteiro.

Q9. Para o objeto WDI, mantenha apenas os registros dos países listados em countries. Selecione as colunas:

- Country Code
- Short Name
- YEAR
- SP.DYN.CBRT.IN
Q10. Ordene o objeto de forma que, para cada país, as informações estejam ordenadas por ano.

Q11. Construa um gráfico de linhas, usando o pacote ggplot2, que tenha no eixo X a variável YEAR, no eixo Y a variável SP.DYN.CBRT.IN e que cada linha corresponda a um país diferente.